name: Python {{ inputs.python-version }}

on:
  workflow_call:
    inputs:
      python-version:
        description: "The version of Python to use"
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Test Environment for Python ${{ inputs.python-version }}
        id: setup-python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}
          poetry-args: "--with test"
      # IMPORTANT: IF RUNNING PYTEST IS NO LONGER THE 3RD STEP, UPDATE THE LINK BELOW TO MATCH THE RIGHT STEP NUMBER
      - name: Run pytest
        run: poetry run pytest --no-header --tb=no --color=yes
      - name: Output Test Summary
        run: |
          echo "### Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Python Version: **${{ steps.setup-python.outputs.python-version }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Env from Cache: **${{ steps.setup-python.outputs.cache-hit }}**" >> $GITHUB_STEP_SUMMARY
          echo "**[Test Results](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/{{ github.job }}#step:4:1)**" >> $GITHUB_STEP_SUMMARY
