name: Python {{ inputs.python-version }}

on:
  workflow_call:
    inputs:
      python-version:
        description: "The version of Python to use"
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Test Environment for Python ${{ inputs.python-version }}
        id: setup-python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}
          poetry-args: "--with test"
      - name: Show Test Summary
        run: |
          echo "### Configuration" >> $GITHUB_STEP_SUMMARY
          echo "| Python | ${{ steps.setup-python.outputs.python-version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Env from Cache | ${{ steps.setup-python.outputs.cache-hit }} |" >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
      - name: Test with pytest
        run: poetry run pytest --no-header --tb=no --color=yes >> $GITHUB_STEP_SUMMARY
