name: Python {{ inputs.python-version }}

on:
  workflow_call:
    inputs:
      python-version:
        description: "The version of Python to use"
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Test Environment for Python ${{ inputs.python-version }}
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ inputs.python-version }}
          poetry-groups: "test"
      - name: Test with pytest
        run: poetry run pytest tests
